
--MEDICATION RECORDS
INSERT INTO public.medications (id, trade_name, generic_name, concentration, presentation, administration_route, pharmaceutical_form, unit_measure, stock_available, stock_alert, controlled, manufacturer, code, updated_at) VALUES
                                                                                                                                                                                                                          (gen_random_uuid(), 'Dolex Forte', 'Acetaminofén', '500 mg', 'Caja x 24 tabletas', 'Oral', 'Tableta', 'mg', 120, 20, FALSE, 'GSK', 'MED-001', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Amoxisol', 'Amoxicilina', '500 mg', 'Caja x 10 cápsulas', 'Oral', 'Cápsula', 'mg', 80, 15, FALSE, 'Tecnoquímicas', 'MED-002', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Ventolin', 'Salbutamol', '100 mcg', 'Inhalador 200 dosis', 'Inhalación', 'Aerosol', 'mcg', 45, 10, FALSE, 'GSK', 'MED-003', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Lasix', 'Furosemida', '40 mg', 'Caja x 20 tabletas', 'Oral', 'Tableta', 'mg', 60, 10, FALSE, 'Sanofi', 'MED-004', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Tramal', 'Tramadol', '50 mg', 'Caja x 10 cápsulas', 'Oral', 'Cápsula', 'mg', 25, 5, TRUE, 'Pfizer', 'MED-005', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Atorvast', 'Atorvastatina', '20 mg', 'Caja x 30 tabletas', 'Oral', 'Tableta', 'mg', 100, 20, FALSE, 'Pfizer', 'MED-006', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Metformina MK', 'Metformina', '850 mg', 'Caja x 30 tabletas', 'Oral', 'Tableta', 'mg', 90, 15, FALSE, 'MK', 'MED-007', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Ibuprofeno MK', 'Ibuprofeno', '400 mg', 'Caja x 20 tabletas', 'Oral', 'Tableta', 'mg', 140, 30, FALSE, 'MK', 'MED-008', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Diazepam', 'Diazepam', '10 mg', 'Caja x 20 tabletas', 'Oral', 'Tableta', 'mg', 15, 5, TRUE, 'Roche', 'MED-009', NOW()),
                                                                                                                                                                                                                          (gen_random_uuid(), 'Omeprazol MK', 'Omeprazol', '20 mg', 'Caja x 14 cápsulas', 'Oral', 'Cápsula', 'mg', 70, 10, FALSE, 'MK', 'MED-010', NOW());

--SPECIALTIES RECORDS
INSERT INTO public.specialties (id, name, description, requires_authorization, avg_attention_time, code, updated_at) VALUES
                                                                                                                (gen_random_uuid(), 'Cardiología', 'Diagnóstico y tratamiento de enfermedades del corazón.', TRUE, 30, 'ESP-001', NOW()),
                                                                                                                (gen_random_uuid(), 'Neurología', 'Estudio del sistema nervioso y sus trastornos.', TRUE, 40, 'ESP-002', NOW()),
                                                                                                                (gen_random_uuid(), 'Medicina Interna', 'Manejo integral del adulto.', FALSE, 25, 'ESP-003', NOW()),
                                                                                                                (gen_random_uuid(), 'Pediatría', 'Atención de niños y adolescentes.', FALSE, 20, 'ESP-004', NOW()),
                                                                                                                (gen_random_uuid(), 'Ginecología', 'Salud reproductiva femenina.', TRUE, 30, 'ESP-005', NOW()),
                                                                                                                (gen_random_uuid(), 'Dermatología', 'Tratamiento de enfermedades de la piel.', FALSE, 15, 'ESP-006', NOW()),
                                                                                                                (gen_random_uuid(), 'Ortopedia', 'Lesiones y enfermedades del sistema musculoesquelético.', TRUE, 35, 'ESP-007', NOW()),
                                                                                                                (gen_random_uuid(), 'Otorrinolaringología', 'Trastornos de oído, nariz y garganta.', FALSE, 20, 'ESP-008', NOW()),
                                                                                                                (gen_random_uuid(), 'Psiquiatría', 'Trastornos mentales y del comportamiento.', TRUE, 45, 'ESP-009', NOW()),
                                                                                                                (gen_random_uuid(), 'Oftalmología', 'Enfermedades de los ojos.', FALSE, 20, 'ESP-010', NOW());

--PROCEDURE RECORDS
INSERT INTO public.procedures (id, name, description, type, estimated_duration_min, required_supplies, requires_stock, base_cost, code, complexity_level, updated_at) VALUES
                                                                                                                                                                  (gen_random_uuid(), 'Sutura simple', 'Cierre de herida superficial.', 'Ambulatorio', 20, 'Guantes, sutura, anestesia', TRUE, 45000.00, 'PROC-001', 'Baja', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Endoscopia digestiva', 'Visualización del tracto digestivo.', 'Diagnóstico', 45, 'Endoscopio, sedación', TRUE, 250000.00, 'PROC-002', 'Alta', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Yeso de extremidad', 'Inmovilización con yeso.', 'Ortopédico', 30, 'Vendas, yeso, guantes', TRUE, 120000.00, 'PROC-003', 'Media', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Extracción de cuerpo extraño', 'Retiro de objeto superficial.', 'Ambulatorio', 15, 'Pinzas, anestesia', TRUE, 60000.00, 'PROC-004', 'Baja', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Biopsia de piel', 'Toma de muestra de tejido.', 'Diagnóstico', 25, 'Bisturí, formol', TRUE, 180000.00, 'PROC-005', 'Media', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Electrocardiograma', 'Evaluación de la actividad cardíaca.', 'Diagnóstico', 10, 'Electrodos', FALSE, 30000.00, 'PROC-006', 'Baja', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Curación avanzada', 'Manejo de heridas complejas.', 'Ambulatorio', 20, 'Gasas, solución salina', TRUE, 70000.00, 'PROC-007', 'Media', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Lavado ótico', 'Limpieza del canal auditivo.', 'Ambulatorio', 15, 'Solución salina, jeringa', FALSE, 25000.00, 'PROC-008', 'Baja', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Colonoscopia', 'Exploración del colon.', 'Diagnóstico', 60, 'Colonoscopio, sedación', TRUE, 300000.00, 'PROC-009', 'Alta', NOW()),
                                                                                                                                                                  (gen_random_uuid(), 'Infiltración articular', 'Aplicación de medicamento en articulación.', 'Ortopédico', 20, 'Jeringa, anestesia', TRUE, 150000.00, 'PROC-010', 'Media', NOW());

--DIAGNOSTIC_AID RECORDS
INSERT INTO public.diagnostic_aids (id, name, type, description, preparation, delivery_time, requires_authorization, code, required_equipment, requires_stock, updated_at) VALUES
                                                                                                                                                                       (gen_random_uuid(), 'Rayos X de tórax', 'Imagenología', 'Imagen del tórax para evaluar pulmones y corazón.', 'No requiere', 2, FALSE, 'DIA-001', 'Equipo de rayos X', FALSE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Hemograma completo', 'Laboratorio', 'Análisis general de células sanguíneas.', 'Ayuno 8 horas', 24, FALSE, 'DIA-002', 'Analizador hematológico', TRUE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Resonancia magnética cerebral', 'Imagenología', 'Estudio detallado del cerebro.', 'Retirar objetos metálicos', 48, TRUE, 'DIA-003', 'Resonador magnético', FALSE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Ecografía abdominal', 'Imagenología', 'Evaluación de órganos abdominales.', 'Ayuno 6 horas', 1, FALSE, 'DIA-004', 'Ecógrafo', FALSE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Prueba de glucosa', 'Laboratorio', 'Medición de niveles de glucosa.', 'Ayuno 8 horas', 4, FALSE, 'DIA-005', 'Analizador químico', TRUE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Uroanálisis', 'Laboratorio', 'Evaluación general de orina.', 'Recolectar muestra', 12, FALSE, 'DIA-006', 'Equipos básicos de laboratorio', TRUE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Electroencefalograma (EEG)', 'Neurofisiología', 'Registro de actividad eléctrica cerebral.', 'Evitar cafeína', 24, TRUE, 'DIA-007', 'Equipo EEG', FALSE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Tomografía axial computarizada (TAC)', 'Imagenología', 'Cortes seccionales del cuerpo.', 'Retirar objetos metálicos', 36, TRUE, 'DIA-008', 'Tomógrafo', FALSE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Prueba de embarazo', 'Laboratorio', 'Detección de hCG en sangre.', 'No requiere', 2, FALSE, 'DIA-009', 'Reactivos rápidos', TRUE, NOW()),
                                                                                                                                                                       (gen_random_uuid(), 'Perfil lipídico', 'Laboratorio', 'Medición de colesterol y triglicéridos.', 'Ayuno 12 horas', 24, FALSE, 'DIA-010', 'Analizador químico', TRUE, NOW());

commit;